// <auto-generated />
namespace WebShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UsunieciePolaTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsunieciePolaTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202102171500401_UsunieciePolaTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
